//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ESFA.DC.OPA.XSRC.Model.XSRC
{
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "root")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Root {

        private RootEntity[] entitiesField;

        private string rulesField;

        private RootInteractiveitems interactiveitemsField;

        private RootRelationship[] relationshipsField;

        private string rulefoldersField;

        private sbyte schemaversionField;

        private bool schemaversionFieldSpecified;

        private string productversionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entity", IsNullable = false)]
        public RootEntity[] entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }

        /// <remarks/>
        public string rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("interactive-items")]
        public RootInteractiveitems interactiveitems {
            get {
                return this.interactiveitemsField;
            }
            set {
                this.interactiveitemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("relationship", IsNullable = false)]
        public RootRelationship[] relationships {
            get {
                return this.relationshipsField;
            }
            set {
                this.relationshipsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rule-folders")]
        public string rulefolders {
            get {
                return this.rulefoldersField;
            }
            set {
                this.rulefoldersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("schema-version")]
        public sbyte schemaversion {
            get {
                return this.schemaversionField;
            }
            set {
                this.schemaversionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemaversionSpecified {
            get {
                return this.schemaversionFieldSpecified;
            }
            set {
                this.schemaversionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("product-version")]
        public string productversion {
            get {
                return this.productversionField;
            }
            set {
                this.productversionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootEntity {

        private RootEntityAttribute[] attributeField;

        private string refField;

        private string idField;

        private string nameField;

        private string containmentrelationshipidField;

        private string containmentparentidField;

        private string publicidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute")]
        public RootEntityAttribute[] attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("containment-relationship-id")]
        public string containmentrelationshipid {
            get {
                return this.containmentrelationshipidField;
            }
            set {
                this.containmentrelationshipidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("containment-parent-id")]
        public string containmentparentid {
            get {
                return this.containmentparentidField;
            }
            set {
                this.containmentparentidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("public-id")]
        public string publicid {
            get {
                return this.publicidField;
            }
            set {
                this.publicidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootEntityAttribute {

        private RootEntityAttributeText textField;

        private RootEntityAttributeProp[] propsField;

        private string nameField;

        private string typeField;

        private string publicnameField;

        /// <remarks/>
        public RootEntityAttributeText text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("prop", IsNullable = false)]
        public RootEntityAttributeProp[] props {
            get {
                return this.propsField;
            }
            set {
                this.propsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("public-name")]
        public string publicname {
            get {
                return this.publicnameField;
            }
            set {
                this.publicnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootEntityAttributeText {

        private string baseField;

        private string parseField;

        /// <remarks/>
        public string @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }

        /// <remarks/>
        public string parse {
            get {
                return this.parseField;
            }
            set {
                this.parseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootEntityAttributeProp {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootInteractiveitems {

        private string foldersField;

        private string screensField;

        private string documentsField;

        /// <remarks/>
        public string folders {
            get {
                return this.foldersField;
            }
            set {
                this.foldersField = value;
            }
        }

        /// <remarks/>
        public string screens {
            get {
                return this.screensField;
            }
            set {
                this.screensField = value;
            }
        }

        /// <remarks/>
        public string documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RootRelationship {

        private string sourceField;

        private string targetField;

        private string textField;

        private string relationshipidField;

        private string reversetextField;

        private string reverserelationshipidField;

        private string typeField;

        private string iscomputedField;

        private string iscontainmentField;

        private string publicidField;

        private string reversepublicidField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("relationship-id")]
        public string relationshipid {
            get {
                return this.relationshipidField;
            }
            set {
                this.relationshipidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("reverse-text")]
        public string reversetext {
            get {
                return this.reversetextField;
            }
            set {
                this.reversetextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("reverse-relationship-id")]
        public string reverserelationshipid {
            get {
                return this.reverserelationshipidField;
            }
            set {
                this.reverserelationshipidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("is-computed")]
        public string iscomputed {
            get {
                return this.iscomputedField;
            }
            set {
                this.iscomputedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("is-containment")]
        public string iscontainment {
            get {
                return this.iscontainmentField;
            }
            set {
                this.iscontainmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("public-id")]
        public string publicid {
            get {
                return this.publicidField;
            }
            set {
                this.publicidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("reverse-public-id")]
        public string reversepublicid {
            get {
                return this.reversepublicidField;
            }
            set {
                this.reversepublicidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
